server:
    port: 9093
spring:
    freemarker:
        charset: UTF-8
        content-type: text/html; charset=utf-8
        request-context-attribute: request
        suffix: .html
        template-loader-path: classpath:/templates
smart:
    sso:
        app-id: demo1
        app-secret: 123456
        server-url: http://127.0.0.1:9090
        timeout: 7200